version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:3.6.13-xenial
    hostname: mongodb
    ports:
      - "27017:27017"
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - MONGODB_ENDPOINT=mongodb://mongodb:27017/test
      - APP_VERSION=0.0.1
    links:
      - "dynamodb"
      - "mongodb"
    depends_on:
      - "dynamodb"
      - "mongodb"
    ports:
      - "3000:3000"
